Repository agiledev-students-fall2022/final-project-team-study-buddy, pull requests merged in 2022-12, with the labels that each got.

#122 Containerize with docker
  back-end/.dockerignore
  back-end/dockerfile
  docker-compose.yml
  front-end/.dockerignore
  front-end/dockerfile
Labels: spike

#123 integrated comments to theme more
  back-end/package-lock.json
  back-end/package.json
  front-end/src/Comments/Comments.css
  front-end/src/Comments/Comments.js
  front-end/src/More/More.js
Labels: task

#126 fixed equal signs in More.js
  front-end/src/More/More.js
Labels: spike

#125 express validation implemented
  back-end/routes/commentRoutes.js
  front-end/src/Comments/api.js
Labels: task

#129 reverted to original code, should fix replies
  front-end/src/Comments/api.js
Labels: bug

#135 changed .id to ._id which was why the comments weren't working
  back-end/routes/commentRoutes.js
  front-end/src/Comments/Comment.js
  front-end/src/Comments/Comments.js
Labels: bug
